baseURL: https://blog.meain.io
disablePathToLower: true
languageCode: en-us
title: meain/blog | ðŸ™Œ
theme: lighter
author: "Abin Simon"

googleAnalytics: ""
disableKinds: ["taxonomy", "taxonomyTerm", "section", "404"]

permalinks:
    post: /:year/:title/
    page: /:filename/

menus:
    main:
        - url: /about/
          name: About
        - url: https://github.com/meain
          name: Github
        - url: https://twitter.com/meain_
          name: Twitter

params:
    favicon: "favicon.png"
    icon:
        url: "favicon.png"
